### ISSUE TITLE
Kong manager with basic auth on apis didn't works on first page

### ISSUE THREAD

**Issue by kamontat** [Kong/kong-manager#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

Kong 3.6.1

### Current Behavior

When I enabled basic auth on both admin apis and manager page, the first page didn't receive information correctly. This problem only occurred on first overview page, for another page it works as expected.

### Expected Behavior

Able to get information and display it correctly on overview page.

### Steps To Reproduce

1. Deploy Hybrid mode on Kubernetes cluster (but I think it might occurred regardless of deployment method)
2. Enabled basic auth on both admin and manager
3. Visit manager website
4. First overview page won't show any data

![CleanShot 2024-09-16 at 16 07 16@2x](https://github.com/user-attachments/assets/fd0c669c-7c69-4eda-8283-7cae05b0d6d0)

5. Another pages will works as expected

![CleanShot 2024-09-16 at 16 08 55@2x](https://github.com/user-attachments/assets/76400199-883e-4544-a1d9-1de82ebd2b3c)

### Anything else?

Network when visit overview page:

![CleanShot 2024-09-16 at 15 58 16@2x](https://github.com/user-attachments/assets/91d82645-8c8d-43e9-8b30-3f2528dd7349)

Network when call admin apis:

![CleanShot 2024-09-16 at 15 58 18@2x](https://github.com/user-attachments/assets/a56e3bcc-2a6a-4b09-99e7-def63cc75e3f)

**Comment by raoxiaoyan** [comment]
@kamontat 
Thank you for your reporting.
It doesn't support `basic-auth` for the Kong manager OSS. I'm curious why do you enable the `basic auth` with Kong Manager OSS?

**Comment by raoxiaoyan** [comment]
By the way. I can't repro this issue. Could you provide the `kong.conf` that you are using?

**Comment by kamontat** [comment]
@raoxiaoyan I didn't use `kong.conf`.

I follow [this](https://docs.konghq.com/gateway/latest/install/kubernetes/proxy/) get-start guide. and enabled basic-auth using plugin on both kong-manager and kong-admin component.

I not familiar with the tool, we are currently just experimenting several tools to see which suitable for our company.

**Comment by raoxiaoyan** [comment]
@kamontat Oh. You should access the Kong Manager with 8002. I think.
But first, you need to enable the Kong Manager in the kic.cp.yml
> # Optional features
> manager:
>    enabled: false

Ref https://docs.konghq.com/gateway/latest/install/kubernetes/proxy/#control-plane

**Comment by kamontat** [comment]
I'm set everything based on articles ([1][1], [2][2]).

I have no problem to configure both admin and manager. However, somehow on first page it don't ask for basic-auth and just send request immediately to admin apis. 


[1]: https://docs.konghq.com/gateway/latest/install/kubernetes/admin/
[2]: https://docs.konghq.com/gateway/latest/install/kubernetes/manager/

**Comment by raoxiaoyan** [comment]
The `basic-auth` only support for Kong Manager(Enterprise Edition). Not for Kong Manager OSS.
