### ISSUE TITLE
Edit Upstream tcp_failures and http_failures values

### ISSUE THREAD

**Issue by Abdoam** [Kong/kong-manager#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Kong version (`$ kong version`)

3.8

### Current Behavior

When open Edit Upstream page some values different from show upstream configuration page

**Example** 

- when open Upstream Configuration page
        - in Active **tcp_failures = 3** and http_failures = 3 
        - in Passive tcp_failures = 2 and **http_failures = 2**
    
![Screenshot from 2024-10-13 04-37-13](https://github.com/user-attachments/assets/16ddf5a9-876a-406d-beec-d09220ebc68c)

But when open edit upstream page values different
    in Active **tcp_failures = 5** and http_failures = 3 
    in Passive tcp_failures = 2 and **http_failures = 5**

![Screenshot from 2024-10-13 04-37-37](https://github.com/user-attachments/assets/379f1130-9b7d-4561-9798-af7e59b8c9e6)  

![Screenshot from 2024-10-13 04-37-49](https://github.com/user-attachments/assets/4674b385-ee3c-4391-b2f8-1d71e749725a)

### Expected Behavior

When open Edit Upstream page values must be same as show in upstream configuration page

### Steps To Reproduce

1- open upstream page
2- add upstream (set tcp_failures and http_failures to value different than 5)
3- save upstream
4- back to upstream page
5- select added upstream to show details
6- click in edit button
7- show values of  tcp_failures and http_failures in edit page

**Comment by Leopoldthecoder** [comment]
Hey @Abdoam, thank you for reporting this issue! I have fixed it in https://github.com/Kong/public-ui-components/pull/1726 and it'll be released with Kong Gateway 3.9.
